Repository GoTogether-Inc/backend, pull requests merged in 2025-03, with the labels that each got.

#29 [fix] 북마크 @DeleteMapping에 대한 엔드포인트 수정 / Merge 전 충돌 해결
  src/main/java/com/gotogether/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/gotogether/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/gotogether/domain/event/facade/EventFacade.java
  src/main/java/com/gotogether/global/apipayload/code/status/ErrorStatus.java
Labels: 🐞 fix

#34 [feature] 카테고리별 이벤트 리스트 조회 / 유저 API 구현
  src/main/java/com/gotogether/domain/event/controller/EventController.java
  src/main/java/com/gotogether/domain/event/repository/EventRepository.java
  src/main/java/com/gotogether/domain/event/service/EventService.java
  src/main/java/com/gotogether/domain/event/service/EventServiceImpl.java
  src/main/java/com/gotogether/domain/user/controller/UserController.java
  src/main/java/com/gotogether/domain/user/converter/UserConverter.java
  src/main/java/com/gotogether/domain/user/dto/request/UserRequestDTO.java
  src/main/java/com/gotogether/domain/user/dto/response/UserDetailResponseDTO.java
  src/main/java/com/gotogether/domain/user/dto/response/package-info.java
  src/main/java/com/gotogether/domain/user/entity/User.java
  src/main/java/com/gotogether/domain/user/service/UserService.java
  src/main/java/com/gotogether/domain/user/service/UserServiceImpl.java
  src/main/java/com/gotogether/global/oauth/handler/CustomSuccessHandler.java
Labels: ✨ feature, ♻️ refactor

#37 [hotfix] Cors 주소 설정
  src/main/java/com/gotogether/global/config/SecurityConfig.java
Labels: 🚨hotfix

#38 [feature] 구매/참가자 관리 API 구현 (대시보드)
  src/main/java/com/gotogether/domain/hostchannel/controller/HostChannelController.java
  src/main/java/com/gotogether/domain/hostchannel/converter/HostChannelConverter.java
  src/main/java/com/gotogether/domain/hostchannel/dto/request/OrderStatusRequestDTO.java
  src/main/java/com/gotogether/domain/hostchannel/dto/response/HostDashboardResponseDTO.java
  src/main/java/com/gotogether/domain/hostchannel/dto/response/ParticipantManagementResponseDTO.java
  src/main/java/com/gotogether/domain/hostchannel/service/HostChannelService.java
  src/main/java/com/gotogether/domain/hostchannel/service/HostChannelServiceImpl.java
  src/main/java/com/gotogether/domain/order/entity/Order.java
  src/main/java/com/gotogether/domain/order/repository/OrderRepository.java
  src/main/java/com/gotogether/domain/ticket/repository/TicketRepository.java
  src/main/java/com/gotogether/domain/user/controller/UserController.java
  src/main/java/com/gotogether/domain/user/service/UserService.java
  src/main/java/com/gotogether/domain/user/service/UserServiceImpl.java
  src/main/java/com/gotogether/global/apipayload/code/status/ErrorStatus.java
Labels: ✨ feature

#40 [refactor] 호스트 채널 삭제 리펙토링 + Event 필드 변경
  src/main/java/com/gotogether/domain/bookmark/converter/BookmarkConverter.java
  src/main/java/com/gotogether/domain/bookmark/dto/response/BookmarkListResponseDTO.java
  src/main/java/com/gotogether/domain/event/converter/EventConverter.java
  src/main/java/com/gotogether/domain/event/dto/request/EventRequestDTO.java
  src/main/java/com/gotogether/domain/event/dto/response/EventDetailResponseDTO.java
  src/main/java/com/gotogether/domain/event/dto/response/EventListResponseDTO.java
  src/main/java/com/gotogether/domain/event/entity/Event.java
  src/main/java/com/gotogether/domain/event/repository/EventRepository.java
  src/main/java/com/gotogether/domain/hostchannel/converter/HostChannelConverter.java
  src/main/java/com/gotogether/domain/hostchannel/dto/request/HostChannelRequestDTO.java
  src/main/java/com/gotogether/domain/hostchannel/entity/HostChannel.java
  src/main/java/com/gotogether/domain/hostchannel/service/HostChannelServiceImpl.java
  src/main/java/com/gotogether/domain/order/converter/OrderConverter.java
  src/main/java/com/gotogether/domain/order/dto/response/OrderedDetailResponseDTO.java
  src/main/java/com/gotogether/domain/order/dto/response/OrderedTicketResponseDTO.java
  src/main/java/com/gotogether/global/apipayload/code/status/ErrorStatus.java
Labels: ♻️ refactor

#45 [feature] 예약 메일 API 구현
  build.gradle
  src/main/java/com/gotogether/domain/alert/entity/Alert.java
  src/main/java/com/gotogether/domain/event/entity/Event.java
  src/main/java/com/gotogether/domain/reservationemail/controller/ReservationEmailController.java
  src/main/java/com/gotogether/domain/reservationemail/converter/ReservationEmailConverter.java
  src/main/java/com/gotogether/domain/reservationemail/dto/request/ReservationEmailRequestDTO.java
  src/main/java/com/gotogether/domain/reservationemail/dto/response/ReservationEmailDetailResponseDTO.java
  src/main/java/com/gotogether/domain/reservationemail/entity/ReservationEmail.java
  src/main/java/com/gotogether/domain/reservationemail/entity/ReservationEmailStatus.java
  src/main/java/com/gotogether/domain/reservationemail/facade/ReservationEmailFacade.java
  src/main/java/com/gotogether/domain/reservationemail/repository/ReservationEmailRepository.java
  src/main/java/com/gotogether/domain/reservationemail/scheduler/EmailScheduler.java
  src/main/java/com/gotogether/domain/reservationemail/scheduler/QuartzJobScheduler.java
  src/main/java/com/gotogether/domain/reservationemail/scheduler/job/ReservationEmailJob.java
  src/main/java/com/gotogether/domain/reservationemail/service/EmailService.java
  src/main/java/com/gotogether/domain/reservationemail/service/EmailServiceImpl.java
  src/main/java/com/gotogether/domain/reservationemail/service/ReservationEmailService.java
  src/main/java/com/gotogether/domain/reservationemail/service/ReservationEmailServiceImpl.java
  src/main/java/com/gotogether/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/gotogether/global/config/MailConfig.java
  src/main/java/com/gotogether/global/config/QuartzConfig.java
Labels: ✨ feature

#47 [chore] JaCoCo 설정 / CICD 브랜치별 분리
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  build.gradle
  src/test/java/com/gotogether/domain/controller/EventControllerTest.java
  src/test/java/com/gotogether/domain/controller/HostChannelControllerTest.java
  src/test/java/com/gotogether/domain/controller/TicketControllerTest.java
Labels: 🎸 chore

#50 [fix] S3 Url DTO 추가
  src/main/java/com/gotogether/global/common/controller/FileUploadController.java
  src/main/java/com/gotogether/global/common/dto/S3UrlResponseDTO.java
  src/main/java/com/gotogether/global/common/service/FileUploadService.java
Labels: 🐞 fix
