Repository GoTogether-Inc/backend, pull requests merged in 2025-07, with the labels that each got.

#164 fix: EventListResponseDTO status 응답 추가
  src/main/java/com/gotogether/domain/event/converter/EventConverter.java
  src/main/java/com/gotogether/domain/event/dto/response/EventListResponseDTO.java
Labels: 🐞 fix

#168 [chore] 운영/개발 환경에 맞게 CI/CD 수정
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: 🎸 chore

#170 [fix] 이벤트 상세 조회 해시태그 응답 추가 및 티켓 목록 조회 startDate, endDate 응답 추가
  src/main/java/com/gotogether/domain/event/converter/EventConverter.java
  src/main/java/com/gotogether/domain/event/dto/response/EventDetailResponseDTO.java
  src/main/java/com/gotogether/domain/ticket/converter/TicketConverter.java
  src/main/java/com/gotogether/domain/ticket/dto/response/TicketListResponseDTO.java
Labels: 🐞 fix

#190 [feat] 구매/참가자 관리 목록 엑셀 다운로드 API 구현
  build.gradle
  src/main/java/com/gotogether/domain/hostchannel/controller/HostChannelApi.java
  src/main/java/com/gotogether/domain/hostchannel/controller/HostChannelController.java
  src/main/java/com/gotogether/domain/hostchannel/service/HostChannelService.java
  src/main/java/com/gotogether/domain/hostchannel/service/HostChannelServiceImpl.java
  src/main/java/com/gotogether/domain/ticketoptionanswer/repository/TicketOptionAnswerRepository.java
  src/main/java/com/gotogether/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/gotogether/global/util/ExcelGenerator.java
Labels: ✨ feature

#193 [feat] 전화번호 인증 API 구현
  build.gradle
  src/main/java/com/gotogether/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/gotogether/global/common/controller/S3UploadApi.java
  src/main/java/com/gotogether/global/common/controller/S3UploadController.java
  src/main/java/com/gotogether/global/common/controller/SmsApi.java
  src/main/java/com/gotogether/global/common/controller/SmsController.java
  src/main/java/com/gotogether/global/common/dto/SmsRequestDTO.java
  src/main/java/com/gotogether/global/common/dto/SmsVerifyRequestDTO.java
  src/main/java/com/gotogether/global/common/service/SmsService.java
  src/main/java/com/gotogether/global/config/RedisConfig.java
  src/main/java/com/gotogether/global/util/SmsCertificationUtil.java
Labels: ✨ feature

#196 [feature] Interceptor 기반 요청/응답 상세 로깅 구현
  src/main/java/com/gotogether/global/config/SecurityConfig.java
  src/main/java/com/gotogether/global/config/WebMVCConfig.java
  src/main/java/com/gotogether/global/filter/CachingRequestResponseFilter.java
  src/main/java/com/gotogether/global/interceptor/LoggingInterceptor.java
  src/main/java/com/gotogether/global/oauth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/gotogether/global/oauth/handler/CustomFailureHandler.java
  src/main/java/com/gotogether/global/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/gotogether/global/oauth/service/CustomOAuth2UserService.java
Labels: ✨ feature

#198 [feat] 요청 바디 로깅 기능 구현
  src/main/java/com/gotogether/global/filter/CachingRequestResponseFilter.java
  src/main/java/com/gotogether/global/interceptor/LoggingInterceptor.java
Labels: ✨ feature
